env:
  browser: true
  es2021: true
extends:
  - airbnb-base
  - prettier
plugins:
  - prettier
parserOptions:
  ecmaVersion: 12
  sourceType: module
parser: '@babel/eslint-parser'
rules:
  {
    'prettier/prettier': ['error'],
    'import/no-extraneous-dependencies':
      [
        'error',
        {
          'devDependencies': true,
          'optionalDependencies': false,
          'peerDependencies': false,
          'packageDir': './',
        },
      ],
    'no-underscore-dangle':
      [
        'error',
        { 'allowAfterThis': true },
        { 'allowAfterSuper': true },
        { 'allowAfterThisConstructor': true },
      ],
  }
